apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/devkishanjoshi/argocd.git # Github repo URL 
    targetRevision: HEAD # Always look for last commit
    path: dev       # Path in github repository 
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:           # If anything is not available then create on the go .. here namespace will be creted
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true      # If anything applied manually to cluster then it will be overwritten 
      prune: true         # If anything deleted in github repo then argocd should also delete that in cluster as well.