apiVersion: v1
kind: Service
metadata:
  name: nodeport-argocd-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
      - name: https
        port: 443
        protocol: TCP
        targetPort: 8080
